version = 1
# Snapshotter's own home directory where it stores and creates necessary resources
root = "/var/lib/containerd-nydus"
# The snapshotter's GRPC server socket, containerd will connect to plugin on this socket
address = "/run/containerd-nydus/containerd-nydus-grpc.sock"
# The nydus daemon mode can be one of the following options: multiple, dedicated, shared, or none. 
# If `daemon_mode` option is not specified, the default value is multiple.
daemon_mode = "multiple"

[daemon]
# Specify a configuration file for nydusd
nydusd_config = "/opt/nydus/conf/nydusd-fusedev.json"
nydusd_path = "/opt/nydus/bin/nydusd"
nydusimage_path = "/opt/nydus/bin/nydus-image"
# fusedev or fscache
fs_driver = "fusedev"

[log]
# Print logs to stdout rather than logging files
log_to_stdout = true
# Snapshotter's log level
level = "info"
